name: CI/CD Pipeline

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: maorsh6/hello-world

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_step.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish App
        run: dotnet publish -c Release -o out

      - name: Set Version
        id: version_step
        run: |
          VERSION=$(git describe --tags --always || echo "v0.0.1")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.version }} .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.version }}
